language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

services:
    - redis-server

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - node_modules
        - vendor

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install -n --no-suggest

script:
    - php vendor/bin/phpunit
